### ISSUE TITLE
What to do with "removal from" in birth place column?

### ISSUE THREAD

**Issue by bmckinney** [Green-Wood-Cemetery/burial-registry-search#31]
example: vol 16, 122504

**Comment by bmckinney** [comment]
From Julie:

I expected to see where it was removed from in remarks, but when I looked at the original it doesn't seem to be anywhere.  Stacy: would love your interpretation on this one. My answer would be it's transcribed correctly and it should be calculated exactly as written, but perhaps I am missing something.

**Comment by StacyEllyn** [comment]
It appears that the data was transcribed correctly, but in the case of #122504, the previous location of the body is not listed. In #122502 for instance, the place where it was removed from is listed across the two late residence columns as "Cypress Hills Cemetery" (You can see the same in #122505 with Calvary Cemetery), however it appears that the former cemetery here wasn't included but just the city (New York). It is very possible that disclosing that information was not required, and thus wasn't recorded by GW.

**Comment by bmckinney** [comment]
a proposal:

- if "removal/removed to/from" is found in fields other than remarks (e.g., death place), delete if from those display fields (except for remarks) since the person didn't actually die at Calvary Cemetery
- append to display version of remarks if it isn't already there
- set new "removed from" or "removed to" boolean columns to true so researchers can search based on this facet

**Comment by bmckinney** [comment]
**BIRTH PLACE**
eg: "removal from"
- display value = "unknown"
- leave transcribed value
- populate new column "burial origin" = "removal from" (simply populate value found in birth place)
 **MARITAL STATUS & AGE - DAY (anywhere where it isn't in remarks column)**
eg: "from cemetery"
- move this value to "displayed remarks"

**Comment by bmckinney** [comment]
see: 5b2c0370aed0837e6bb584c2d732c1686cfbb6dc
