### ISSUE TITLE
ED and NY are being replaced where they shouldn't be

### ISSUE THREAD

**Issue by bmckinney** [Green-Wood-Cemetery/burial-registry-search#38]
vol 17, 134587 (germaNY)

**Comment by bmckinney** [comment]
@StacyEllyn I'm seeing this in the original IDI spreadsheet that I never touch.

**Comment by StacyEllyn** [comment]
Ah ok! I'm so sorry, I think I was looking at the wrong spreadsheet when we were chatting. Thank you for verifying.
